"""Add registered_at and confirmed columns to UserModel.

Revision ID: 12f5f2f8690b
Revises: 94a8324c008f
Create Date: 2024-10-29 21:34:54.011607

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "12f5f2f8690b"
down_revision = "94a8324c008f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "topic",
        "categorys",
        existing_type=postgresql.ENUM(
            "paintings", "web_design", "photography", name="categorys"
        ),
        type_=sa.Enum("paintings", "web_design", "photography", name="categorys"),
        existing_nullable=False,
    )
    op.add_column("users", sa.Column("registered_at", sa.DateTime(), nullable=False))
    op.add_column("users", sa.Column("confirmed", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "confirmed")
    op.drop_column("users", "registered_at")
    op.alter_column(
        "topic",
        "categorys",
        existing_type=sa.Enum(
            "paintings", "web_design", "photography", name="categorys"
        ),
        type_=postgresql.ENUM(
            "paintings", "web_design", "photography", name="categorys"
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
