"""Add Topic and Post tables to database.

Revision ID: 22765333cc4d
Revises: f8c001aee32f
Create Date: 2024-02-21 23:04:36.544079

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "22765333cc4d"
down_revision = "f8c001aee32f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "topic",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("topic_name", sa.String(length=255), nullable=False),
        sa.Column(
            "categorys",
            sa.Enum("paintings", "web_design", "photography", name="categorys"),
            nullable=False,
        ),
        sa.Column("topic_creation_date_time", sa.DateTime(), nullable=True),
        sa.Column("topic_author", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["topic_author"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "post",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text_of_post", sa.Text(), nullable=False),
        sa.Column("date_time_of_post", sa.DateTime(), nullable=True),
        sa.Column("post_to_topic", sa.Integer(), nullable=False),
        sa.Column("post_author", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["post_author"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["post_to_topic"],
            ["topic.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("post")
    op.drop_table("topic")
    # ### end Alembic commands ###
