"""empty message

Revision ID: 2f18b3ea9c6b
Revises: d86bccf1dcfd
Create Date: 2024-11-07 16:30:04.500901

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2f18b3ea9c6b"
down_revision = "d86bccf1dcfd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "topic", sa.Column("topic_last_update_date_time", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("topic", "topic_last_update_date_time")
    # ### end Alembic commands ###
