"""Change role column to nullable false in user model.

Revision ID: 34a9b1a19605
Revises: 89fe8578d638
Create Date: 2024-03-30 14:56:11.381849

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "34a9b1a19605"
down_revision = "89fe8578d638"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "topic",
        "categorys",
        existing_type=postgresql.ENUM(
            "paintings", "web_design", "photography", name="categorys"
        ),
        type_=sa.Enum("paintings", "web_design", "photography", name="categorys"),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "role",
        existing_type=postgresql.ENUM("admin", "user", "moderator", name="roletype"),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "role",
        existing_type=postgresql.ENUM("admin", "user", "moderator", name="roletype"),
        nullable=True,
    )
    op.alter_column(
        "topic",
        "categorys",
        existing_type=sa.Enum(
            "paintings", "web_design", "photography", name="category"
        ),
        type_=postgresql.ENUM(
            "paintings", "web_design", "photography", name="categorys"
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
