"""Delete post author and topic author columns.

Revision ID: 4b4faddb3372
Revises: a99cee7fd6b6
Create Date: 2024-03-02 17:19:30.130524

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4b4faddb3372'
down_revision = 'a99cee7fd6b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('post_post_author_fkey', 'post', type_='foreignkey')
    op.drop_column('post', 'post_author')
    op.alter_column('topic', 'categorys',
               existing_type=postgresql.ENUM('paintings', 'web_design', 'photography', name='categorys'),
               type_=sa.Enum('paintings', 'web_design', 'photography', name='categorys'),
               existing_nullable=False)
    op.drop_constraint('topic_topic_author_fkey', 'topic', type_='foreignkey')
    op.drop_column('topic', 'topic_author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('topic_author', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('topic_topic_author_fkey', 'topic', 'users', ['topic_author'], ['id'])
    op.alter_column('topic', 'categorys',
               existing_type=sa.Enum('paintings', 'web_design', 'photography', name='category'),
               type_=postgresql.ENUM('paintings', 'web_design', 'photography', name='categorys'),
               existing_nullable=False)
    op.add_column('post', sa.Column('post_author', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('post_post_author_fkey', 'post', 'users', ['post_author'], ['id'])
    # ### end Alembic commands ###
