"""Create projects and images tables, add relationship user-project.

Revision ID: 7dd0826b45b9
Revises: bd1387e1dac3
Create Date: 2024-03-05 16:22:26.614354

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "7dd0826b45b9"
down_revision = "bd1387e1dac3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "topic",
        "categorys",
        existing_type=postgresql.ENUM(
            "paintings", "web_design", "photography", name="categorys"
        ),
        type_=sa.Enum("paintings", "web_design", "photography", name="categorys"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "topic",
        "categorys",
        existing_type=sa.Enum(
            "paintings", "web_design", "photography", name="category"
        ),
        type_=postgresql.ENUM(
            "paintings", "web_design", "photography", name="categorys"
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
