"""Add role column in user model and RoleType enum.

Revision ID: 89fe8578d638
Revises: 59ff48dfd062
Create Date: 2024-03-30 14:45:13.356762

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '89fe8578d638'
down_revision = '59ff48dfd062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('topic', 'categorys',
               existing_type=postgresql.ENUM('paintings', 'web_design', 'photography', name='categorys'),
               type_=sa.Enum('paintings', 'web_design', 'photography', name='categorys'),
               existing_nullable=False)
    role = postgresql.ENUM('admin', 'user', 'moderator', name='roletype', create_type=False)
    role.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('role', sa.Enum('admin', 'user', 'moderator', name='roletype'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.alter_column('topic', 'categorys',
               existing_type=sa.Enum('paintings', 'web_design', 'photography', name='category'),
               type_=postgresql.ENUM('paintings', 'web_design', 'photography', name='categorys'),
               existing_nullable=False)
    # ### end Alembic commands ###
