"""Add project_last_update_date_time column in projects model.

Revision ID: 9b400a3502fb
Revises: b950953f4ee7
Create Date: 2024-03-21 21:33:07.114325

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9b400a3502fb"
down_revision = "b950953f4ee7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column("project_last_update_date_time", sa.DateTime(), nullable=True),
    )
    op.alter_column(
        "topic",
        "categorys",
        existing_type=postgresql.ENUM(
            "paintings", "web_design", "photography", name="categorys"
        ),
        type_=sa.Enum("paintings", "web_design", "photography", name="categorys"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "topic",
        "categorys",
        existing_type=sa.Enum(
            "paintings", "web_design", "photography", name="category"
        ),
        type_=postgresql.ENUM(
            "paintings", "web_design", "photography", name="categorys"
        ),
        existing_nullable=False,
    )
    op.drop_column("projects", "project_last_update_date_time")
    # ### end Alembic commands ###
