"""Add unique constraint and default value to username column in users table.

Revision ID: a99cee7fd6b6
Revises: cf96ac3f36bc
Create Date: 2024-03-02 12:53:13.337520

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a99cee7fd6b6'
down_revision = 'cf96ac3f36bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.alter_column('categorys',
               existing_type=postgresql.ENUM('paintings', 'web_design', 'photography', name='categorys'),
               type_=sa.Enum('paintings', 'web_design', 'photography', name='categorys'),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.alter_column('categorys',
               existing_type=sa.Enum('paintings', 'web_design', 'photography', name='category'),
               type_=postgresql.ENUM('paintings', 'web_design', 'photography', name='categorys'),
               existing_nullable=False)

    # ### end Alembic commands ###
