"""Create post author and topic author columns as strings type.

Revision ID: bd1387e1dac3
Revises: 4b4faddb3372
Create Date: 2024-03-02 17:25:35.806105

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bd1387e1dac3'
down_revision = '4b4faddb3372'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('post_author', sa.String(length=255), nullable=True))
    op.add_column('topic', sa.Column('topic_author', sa.String(length=255), nullable=True))
    op.alter_column('topic', 'categorys',
               existing_type=postgresql.ENUM('paintings', 'web_design', 'photography', name='categorys'),
               type_=sa.Enum('paintings', 'web_design', 'photography', name='categorys'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('topic', 'categorys',
               existing_type=sa.Enum('paintings', 'web_design', 'photography', name='category'),
               type_=postgresql.ENUM('paintings', 'web_design', 'photography', name='categorys'),
               existing_nullable=False)
    op.drop_column('topic', 'topic_author')
    op.drop_column('post', 'post_author')
    # ### end Alembic commands ###
