"""empty message

Revision ID: d65917d10d2d
Revises: 6ec790aed289
Create Date: 2024-11-06 10:31:51.442473

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d65917d10d2d"
down_revision = "6ec790aed289"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "topic",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("topic_name", sa.String(length=255), nullable=False),
        sa.Column(
            "categorys",
            sa.Enum("paintings", "web_design", "photography", name="category"),
            nullable=False,
        ),
        sa.Column("topic_creation_date_time", sa.DateTime(), nullable=True),
        sa.Column("topic_author", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("registered_at", sa.DateTime(), nullable=False),
        sa.Column("confirmed", sa.Boolean(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("admin", "user", "moderator", name="roletype"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "post",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text_of_post", sa.Text(), nullable=False),
        sa.Column("date_time_of_post", sa.DateTime(), nullable=True),
        sa.Column("post_author", sa.String(length=255), nullable=True),
        sa.Column("post_to_topic", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["post_to_topic"],
            ["topic.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_name", sa.String(length=255), nullable=False),
        sa.Column("project_description", sa.Text(), nullable=False),
        sa.Column("project_creation_date_time", sa.DateTime(), nullable=True),
        sa.Column("project_last_update_date_time", sa.DateTime(), nullable=True),
        sa.Column("project_views_counter", sa.Integer(), nullable=True),
        sa.Column("project_author", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_author"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "images",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("image_url", sa.String(length=255), nullable=False),
        sa.Column("image_uploading_date_time", sa.DateTime(), nullable=True),
        sa.Column("image_to_project", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["image_to_project"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("images")
    op.drop_table("projects")
    op.drop_table("post")
    op.drop_table("users")
    op.drop_table("topic")
    # ### end Alembic commands ###
