"""empty message

Revision ID: d86bccf1dcfd
Revises: d65917d10d2d
Create Date: 2024-11-07 15:05:25.677319

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d86bccf1dcfd"
down_revision = "d65917d10d2d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "post", sa.Column("date_time_of_create_post", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "post", sa.Column("date_time_of_update_post", sa.DateTime(), nullable=True)
    )
    op.drop_column("post", "date_time_of_post")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "post",
        sa.Column(
            "date_time_of_post",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("post", "date_time_of_update_post")
    op.drop_column("post", "date_time_of_create_post")
    # ### end Alembic commands ###
